language: java
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - ATOMIST_REPO_USER=travis-mvn-deploy
  - secure: kJLZHKx9JpeI32AIsqBecS5YfFJArHhhX4X2TeOISnUkBa/YLWn03ZKKSGxG0bYWn8LKDIXE1agOkzAQ6AHSPRz3WbcuQ0BqmlZ1LTVbKW8BDLABQGQr5kJ1SVWtaLRHXGNusJyJwABq9QEfnpEksOmXzCQVf0VTKc/8ABB/quhng/HAwvRKIXwRi3WxY+V6HhgOcrJn57SJ0VFJF1LZlvhWYq+HrEq559P9EOVuM4qLIerBRwLIfimpDBzgbUQOf8SFU0Obt2VaD+BqAdmc/fYY/nSNjFDFECGzcik8AZOWkFgSuG4fvoY3DUn1et75VXmssnB9NBd4QKgLp4xs91pV/MHSF+mB01LwEltu1TZZkyJ7eTSAnpq5veS+pp2K9tjfDkxH1fUz7HGihg87uZfZe4IY71VikKwmKCTj2ulDacXPl3p9I9GewuNYJX8KZM1sY/Hks+SYJl7eD9v93Fw+I+qLIgapEK6QSTum1tpJ4oY1uqW1eBBdWr90C967dDKKN+JqSrgEdR0hSRVW5jWK/UMC/ZINn/edzp2zYskLv5BMAIDDGEh3gwHIH2ubHqDYsE6VEF1ETP7RAK1dOBXVzxd03I6in+H1Ra6g9A4IH78GhQ1HOdtwl2jqIWrHAiTea7QnVkoQahT/1WiMJZ0xOXzLLrQ7APfgu5BK7Ik=
  - secure: HQTJwX797f5zDA8APkFZ8NyJZMtGVuH2jZZv01CsUZ0rsmLs7MfoxDnevHemVD8vN/Q0YB8pTSdZZ89S/BO/PW4qz0J9eyWVkGx8nQJlVkjba45EpJxbPrK+6qfTbfD2W20wekII5poscaeeJJ//eMzsBmS78i+3CAhFdmBoEVK4p1Pr7EZTkULC9Z2cD+eUkLXnRo/9VDdmBY5meOebJTXWvAcTOHXDeK+aV3+k++ZHgodZsSUFWhiLKhiODlb1ayrzh14y7Z3BgkrQRM+Erv0g8ULDLsHpbeuxb2rFpfiiWshcam+KWiOKJIh0veRangTBXxoFN0/cxpKFVJXRw3o6iseWEEhG1IncnBi/fQVA7pbXNTmzckeX7zTj0LmwZb2g93kyAycHSyfbCDyFykB+C/GoDwbKJ9EGiCJXeEfcXg2rYgoTQW+VtZjFirSRSv2RQR6CQJgtCc2k7KeaQeeb2sVnKqUIHKICz5BnfGrX+BVR0IdjWedtrTp7hsnmND1r5O3lfxgP3e9r5N+6ifytghzOwoZjtefySaO+wmftfS/mVr7svbwAwLKWufW5nRSC0Lp22uBCYAnfZyG2nIwBjQE1cUJ3e8cJWTk6/Om5cA8Wn/M0wR/7AiJcvKhPgGZTXCxoEjZrNq1UhMFoIL1Bi7Mh2Err5al8PUte3xs=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: releases
  api_key:
    secure: HgbzVU2R1G+jOVGcBTn43pkD6Ver9JR+YpzBeUyYYHG1v0NXMgvHfte5lHOqOOnHhMGjIZqdvn2nLt6PBp8lhCw7E64iXrvrnacH9foz8+DfsDxPMiOJq1u3kGH1XawAjn7wqsDk8h/U/MSOIjnEew6O9uhw0EXkKN+6mXc7qY6VPHxqjPjjY4x5RXnNsYIOjaZ2ZTHMt4YUtantTeYcu5Sga5PIcE7io8FzX2MAzDpgznK9uijBAMe31P8x6Q57yPOz6ifQC/rfZ1krzoaRc5TIv8gZ7szSi+yVhtby6zrZB2XbgMDo4btbOr8UPyYcv+lTayvPP7M0k2vJl+Uo35q1BzyWj4InC8VqyxYp3zErr5IHx93yaG7A+fZyhsrTJZKYBjAq8vhkVbQIMM80h6amjsQ6uk9ZtMw1AQw9P1sofwNGMbAIGQXvpW+PsIuV18SvohWMhRRC0QNPXgrqg0Z1ruCDm2041MrPInuZDWEyWqBQxPPQ/wreeLfJpsMhLlB5Yqw+RBFLMsFpol91AeJMkkPCxjqTcVoWq9v7TnyftdhobXoqQQu98xJ9iN87FpNQwIBont2u+od1334Ygc8vvf/bZJkDfUotbGOCXhUEdrAFtStVCh+cfG7gOxvMWrPz06nlXxcDaxfwlxnWPuV6JLgEsJ7X8I72plun8BU=
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
