language: java
install: true
sudo: tree  
script: bash travis-build.bash
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
branches:
  except:
  - "/\\+travis\\d+$/"
env:
  global:
  - secure: Nj9hzVkDj+V6BB7Hebagj1KZZsiNRpvsP4L2ENnoAK1r00vYrfIzWGcapNcd0mIYdscF1j7nIR+YPbtESNDXgYmEolSNvjLdKXArP7GO0e6AHADEE6blxw3WAm1gq9/2AK1vtsGFQCdkfTGUAaRsU4Ys1+LIyGjivrS9fE9or25dR2t2upDNfvt2Z8iVllL7apW1y8eYvARKJvagA8L6JUL8/k6Jzhal6qkQkWzZGLpyHZR7YAdjRkTiW3Kevn86QAhTNNAE6ZXFAh9Rp90c7EkUWSEIMc9PXZfQwwohxVU/XKYVw+yY+xegxLQcXa9BplFEUYVc8Oix8UJftouV11XOv/09oHj28wVAcPUt+cCHJnhXRRV/St1mOODfZoCIic1Hl9NKIFnDRKb08InrAGVxG4PPBqN2eINxBEpohXD/yy0At1ZI1BM2r5UIv29sny21ICtpz9MWqgr8rTngl85Osw21IyjM8UPqJ0qt+LVWfny1a8LvqxFfMWWD/G3CbvrZ78JtzfRerkVdFgmqz5bfcNdU9SPGhbrOtYW2vO8JvciVt89Bv1JuJMUdS/MYK/RzWYNAHLj68WUqujOd6uNnXikLIPspF/a2n2Ku+rkbT73GUBjYOC2kLRNA7OuPujsLaH+peCQPkZZMBgBqNjWIIu/0gGWUWwykyj+xH/8=
  - secure: sDUrCWR/woweLWWyIX4QKNGFr4mdQkzsYFEOUqln1CmRluX6ymP/h38GrfZX/k/xbYdExYOHt/O8sA0XCb6AVu5JlxXDeTcQ5G72UnX8SL323cEjdLt07XhnTnJsw25n2qHOVClz+HY0bFa6x2PujiyQ2YNfCoUylhpkR63xszpy+5qWMhJ7EyabcampHKrWBlLzPitCGRgOxFv2oXimRzx26cvKntdQDE1nyqNvyatM5kiGomQ8y0xxQkO7iYSbGVE+v3PRXBYBZ0v4SN2KhtYVDGYzxJZ31Uu9ewMXahfhYSI5brjXgZOq/bxP7U85Mljpseb33OBQ96gCfEiEIl4kP8mLn9Kf+f+lFSYzpwxDQ+sIq5vHPizKF/whcQBadHUb6og8qOzx5WdJyyNWQxMIJFFHyY3veURQsjf3Lb6k0CHrfszeXmfzdDDbve1FCuJDMe2gFlJGhECDw6MwQtcTRBt7HaYY8yH9OeGoOQz/QAbsrIZS7NaO4etgrGAS3gHfKTLi0sZwRkGUwH72Hq3gnErZLU34cRQ5xL6eExql4fw2OeL2y9L6lzXiXSoqtfKMxDPAEgGkjhm5DpBiMDw9P9e8M5L5bebUDYqWv8OTfK4DSx8H2CGVuHzxNd9vuV9tHQYY+B1sp4XW0lWkYqTf3X5CsXgTtXjvSKXUaaM=
  - secure: XBUIIBVE+41rOvDAUWu0FZZiT8f3h4ifdTx11Owk/o8qMhGgF4hR8LfLVER+o0jTyIpNKI3uTDNHDu8rij2ltRydnFKV9smB0nZc7tzNgrsANXJ4iTX5WLd5TEzHE63v9Vp3zRybLgjhJUxpyM4UbmjLTlGrwQ3/rq3jTS5k7hbG4jr/zkXLkyU8CWf/mLk47N/oSKH5wHrsP6kmCEGaCncvZ3R3QP9vPwJdMpmq8Kgp1VdZpswOxxnN6HC3hob6aXuf7oIlXGL0VjdSJrW8/KZgTF6lkJSRrkxRjxpJt0WF6Oik6OfTQcSei297m6e8wBmfzsIMFwyz3P6ETTS755jjdz6Jq/aQnBdq04Ypi2WcAV63HB/d2mjpVSMfQMPhwOZxlIsdgVAujZcAycewKVCFVbeyulSo2r6sm6dAE67nFT5yx1g5pIeta6Lb5a0wRiz7l4wP+IGN7psDFazgNIgwWh1reZnK7NwhHgJcsN5F1FwbdzkIqZPGowfORhxGA+qS7pZrcH67npJaPFEDaYvnYoxqAKYXeycAgQAxG0wrsZSQri2Y/QjRGc2wjOckNe5uPqMA5dqTMaER2AQs0vzcQzVTqV2OAXv7nypbyoYPrGe1TrMzdu069G2dIYfxqoT6RPa39Tn7a2+wLpUqMY+hJtE40JCWeZMggEU/yWs=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: releases
  api_key:
    secure: HgbzVU2R1G+jOVGcBTn43pkD6Ver9JR+YpzBeUyYYHG1v0NXMgvHfte5lHOqOOnHhMGjIZqdvn2nLt6PBp8lhCw7E64iXrvrnacH9foz8+DfsDxPMiOJq1u3kGH1XawAjn7wqsDk8h/U/MSOIjnEew6O9uhw0EXkKN+6mXc7qY6VPHxqjPjjY4x5RXnNsYIOjaZ2ZTHMt4YUtantTeYcu5Sga5PIcE7io8FzX2MAzDpgznK9uijBAMe31P8x6Q57yPOz6ifQC/rfZ1krzoaRc5TIv8gZ7szSi+yVhtby6zrZB2XbgMDo4btbOr8UPyYcv+lTayvPP7M0k2vJl+Uo35q1BzyWj4InC8VqyxYp3zErr5IHx93yaG7A+fZyhsrTJZKYBjAq8vhkVbQIMM80h6amjsQ6uk9ZtMw1AQw9P1sofwNGMbAIGQXvpW+PsIuV18SvohWMhRRC0QNPXgrqg0Z1ruCDm2041MrPInuZDWEyWqBQxPPQ/wreeLfJpsMhLlB5Yqw+RBFLMsFpol91AeJMkkPCxjqTcVoWq9v7TnyftdhobXoqQQu98xJ9iN87FpNQwIBont2u+od1334Ygc8vvf/bZJkDfUotbGOCXhUEdrAFtStVCh+cfG7gOxvMWrPz06nlXxcDaxfwlxnWPuV6JLgEsJ7X8I72plun8BU=
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"
